import { makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useAppStyles = makeStyles({
	page: {
		color: "rgba(255, 255, 255, 0.956)",
		minHeight: "100vh",
		backgroundColor: "transparent",
	},
	shell: {
		marginInline: "auto",
		maxWidth: "1160px",
		paddingTop: "0",
		paddingRight: "20px",
		paddingBottom: "72px",
		paddingLeft: "20px",
		display: "grid",
		rowGap: "20px",
		fontFamily: '"Segoe UI Variable Text", "Manrope", "Segoe UI", sans-serif',
		"@media (min-width: 1024px)": {
			rowGap: "24px",
		},
	},
	topBar: {
		position: "sticky",
		top: "0",
		zIndex: "100",
		display: "flex",
		flexWrap: "wrap",
		justifyContent: "space-between",
		alignItems: "center",
		gap: "12px",
		paddingTop: "12px",
		paddingBottom: "12px",
		marginLeft: "-20px",
		marginRight: "-20px",
		paddingLeft: "20px",
		paddingRight: "20px",
		backgroundColor: "rgba(16, 16, 16, 0.9)",
		backdropFilter: "blur(28px) saturate(180%)",
		borderBottom: "1px solid rgba(255, 255, 255, 0.06)",
	},
	brand: {
		display: "inline-flex",
		alignItems: "center",
		gap: "8px",
		color: "rgba(255, 255, 255, 0.92)",
		fontWeight: tokens.fontWeightSemibold,
		letterSpacing: "-0.01em",
	},
	topLinks: {
		display: "flex",
		flexWrap: "wrap",
		gap: "8px",
	},
	topLinkButton: {
		backgroundColor: "rgba(255, 255, 255, 0.055)",
		...shorthands.border("1px", "solid", "rgba(255, 255, 255, 0.083)"),
		color: "rgba(255, 255, 255, 0.78)",
	},
	banner: {
		display: "inline-flex",
		alignItems: "center",
		gap: "8px",
		width: "fit-content",
		...shorthands.padding("6px", "12px"),
		...shorthands.borderRadius(tokens.borderRadiusLarge),
		backgroundColor: "rgba(0, 120, 212, 0.14)",
		...shorthands.border("1px", "solid", "rgba(96, 174, 255, 0.35)"),
		color: "#60AEFF",
		marginTop: "2rem",
	},
	heroCard: {
		backgroundColor: "rgba(30, 30, 30, 0.82)",
		...shorthands.border("1px", "solid", "rgba(255, 255, 255, 0.083)"),
		display: "grid",
		rowGap: "20px",
		overflow: "visible",
		"@media (min-width: 900px)": {
			...shorthands.padding("36px"),
			rowGap: "24px",
		},
	},
	heroTopRow: {
		display: "flex",
		flexDirection: "column",
		gap: "32px",
		"@media (min-width: 1080px)": {
			flexDirection: "row",
			justifyContent: "space-between",
			alignItems: "start",
			gap: "48px",
		},
	},
	heroHeading: {
		marginTop: "0",
		marginBottom: "0",
		fontFamily:
			'"Segoe UI Variable Display", "Space Grotesk", "Trebuchet MS", sans-serif',
		fontSize: "clamp(1.8rem, 6vw, 3.6rem)",
		letterSpacing: "-0.025em",
		lineHeight: "1.1",
		color: "#ffffff",
		fontWeight: "700",
	},
	heroDescription: {
		marginTop: "16px",
		marginBottom: "0",
		fontSize: "clamp(1rem, 2vw, 1.15rem)",
		color: "rgba(255, 255, 255, 0.62)",
		maxWidth: "60ch",
		lineHeight: "1.72",
	},
	releaseCard: {
		display: "grid",
		rowGap: "8px",
		width: "100%",
		maxWidth: "320px",
		...shorthands.padding("24px"),
		...shorthands.border("1px", "solid", "rgba(255, 255, 255, 0.08)"),
		...shorthands.borderRadius(tokens.borderRadiusLarge),
		backgroundColor: "rgba(255, 255, 255, 0.04)",
		"@media (min-width: 1080px)": {
			width: "auto",
			minWidth: "240px",
		},
	},
	releaseTitle: {
		color: "rgba(255, 255, 255, 0.45)",
		letterSpacing: "0.05em",
		textTransform: "uppercase",
	},
	releaseValue: {
		color: "#ffffff",
		fontWeight: tokens.fontWeightSemibold,
		fontSize: "1.25rem",
	},
	buttonRow: {
		display: "flex",
		flexWrap: "wrap",
		gap: "12px",
		width: "100%",
		"& > *": {
			flexGrow: 1,
			flexBasis: "calc(50% - 12px)",
			minWidth: "min(100%, 260px)",
		},
		"@media (max-width: 600px)": {
			"& > *": {
				flexBasis: "100%",
			},
		},
	},
	primaryButton: {
		width: "100%",
		backgroundColor: "#0078D4",
		color: "#ffffff",
		...shorthands.border("1px", "solid", "#0078D4"),
		fontWeight: tokens.fontWeightSemibold,
		":hover": {
			backgroundColor: "#1a86e0",
			color: "#ffffff",
		},
		":active": {
			backgroundColor: "#006cbf",
			color: "#ffffff",
		},
	},
	ghostButton: {
		width: "100%",
		backgroundColor: "rgba(255, 255, 255, 0.055)",
		...shorthands.border("1px", "solid", "rgba(255, 255, 255, 0.1)"),
		color: "rgba(255, 255, 255, 0.82)",
	},
	dropdownContainer: {
		position: "relative",
		width: "100%",
	},
	dropdownButton: {
		width: "100%",
		backgroundColor: "rgba(255, 255, 255, 0.055)",
		...shorthands.border("1px", "solid", "rgba(255, 255, 255, 0.1)"),
		color: "rgba(255, 255, 255, 0.88)",
	},
	dropdownMenu: {
		position: "absolute",
		top: "calc(100% + 8px)",
		right: "0",
		width: "min(92vw, 420px)",
		maxHeight: "320px",
		overflowY: "auto",
		zIndex: "30",
		backgroundColor: "rgba(24, 24, 24, 0.96)",
		backdropFilter: "blur(20px)",
		...shorthands.border("1px", "solid", "rgba(255, 255, 255, 0.12)"),
		...shorthands.borderRadius(tokens.borderRadiusLarge),
		...shorthands.padding("8px"),
		boxShadow: "0 18px 44px rgba(0, 0, 0, 0.55)",
	},
	dropdownTitle: {
		color: "rgba(255, 255, 255, 0.72)",
		...shorthands.padding("8px", "10px", "6px", "10px"),
		letterSpacing: "0.01em",
	},
	dropdownItem: {
		display: "grid",
		rowGap: "2px",
		...shorthands.padding("10px"),
		...shorthands.borderRadius(tokens.borderRadiusMedium),
		textDecorationLine: "none",
		color: "rgba(255, 255, 255, 0.9)",
		":hover": {
			backgroundColor: "rgba(255, 255, 255, 0.08)",
		},
	},
	dropdownItemMeta: {
		color: "rgba(255, 255, 255, 0.52)",
	},
	dropdownList: {
		listStyleType: "none",
		...shorthands.padding(0),
		...shorthands.margin(0),
	},
	statsGrid: {
		display: "grid",
		gap: "12px",
		"@media (min-width: 860px)": {
			gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
		},
	},
	statCard: {
		backgroundColor: "rgba(30, 30, 30, 0.78)",
		...shorthands.border("1px", "solid", "rgba(255, 255, 255, 0.07)"),
		...shorthands.borderRadius(tokens.borderRadiusLarge),
		...shorthands.padding("16px"),
		display: "grid",
		rowGap: "6px",
		minHeight: "88px",
	},
	statCardSpanTwo: {
		"@media (min-width: 860px)": {
			gridColumn: "span 2",
		},
	},
	statCardSpanFour: {
		"@media (min-width: 860px)": {
			gridColumn: "1 / -1",
		},
	},
	statValue: {
		color: "#ffffff",
		fontFamily:
			'"Segoe UI Variable Display", "Space Grotesk", "Trebuchet MS", sans-serif',
		fontSize: "1.3rem",
		fontWeight: tokens.fontWeightSemibold,
	},
	statLabel: {
		color: "rgba(255, 255, 255, 0.50)",
	},
	contentGrid: {
		display: "grid",
		gap: "14px",
		"@media (min-width: 900px)": {
			gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
		},
	},
	twoColumnContentGrid: {
		display: "grid",
		gap: "14px",
		"@media (min-width: 900px)": {
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
		},
	},
	card: {
		backgroundColor: "rgba(30, 30, 30, 0.78)",
		...shorthands.border("1px", "solid", "rgba(255, 255, 255, 0.075)"),
		...shorthands.borderRadius(tokens.borderRadiusLarge),
		...shorthands.padding("20px"),
		display: "grid",
		rowGap: "10px",
	},
	featureTitle: {
		color: "rgba(255, 255, 255, 0.92)",
	},
	featureDescription: {
		color: "rgba(255, 255, 255, 0.54)",
		lineHeight: "1.65",
	},
	screenshotImage: {
		width: "100%",
		height: "auto",
		display: "block",
		transition: "transform 0.6s cubic-bezier(0.16, 1, 0.3, 1)",
		":hover": {
			transform: "scale(1.01)",
		},
	},
	screenshotsGrid: {
		display: "grid",
		gap: "16px",
		gridTemplateColumns: "repeat(1, minmax(0, 1fr))",
		"@media (min-width: 768px)": {
			gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
		},
		marginTop: "16px",
	},
	screenshotCard: {
		backgroundColor: "rgba(0, 0, 0, 0.2)",
		...shorthands.border("1px", "solid", "rgba(255, 255, 255, 0.08)"),
		...shorthands.borderRadius(tokens.borderRadiusLarge),
		overflow: "hidden",
	},
	widgetsCard: {
		backgroundColor: "rgba(28, 28, 28, 0.82)",
		...shorthands.border("1px", "solid", "rgba(255, 255, 255, 0.08)"),
		...shorthands.borderRadius(tokens.borderRadiusLarge),
		...shorthands.padding("24px"),
		display: "grid",
		rowGap: "16px",
	},
	longFormSection: {
		backgroundColor: "rgba(27, 27, 27, 0.8)",
		...shorthands.border("1px", "solid", "rgba(255, 255, 255, 0.08)"),
		...shorthands.borderRadius(tokens.borderRadiusLarge),
		...shorthands.padding("24px"),
		display: "grid",
		rowGap: "14px",
	},
	sectionHeading: {
		marginTop: "0",
		marginBottom: "0",
		color: "#ffffff",
		letterSpacing: "-0.01em",
	},
	sectionLead: {
		marginTop: "0",
		marginBottom: "0",
		color: "rgba(255, 255, 255, 0.66)",
		lineHeight: "1.75",
		maxWidth: "78ch",
	},
	bulletList: {
		marginTop: "0",
		marginBottom: "0",
		paddingLeft: "18px",
		display: "grid",
		rowGap: "10px",
		color: "rgba(255, 255, 255, 0.64)",
		lineHeight: "1.7",
	},
	communityNotice: {
		marginTop: "0",
		marginBottom: "0",
		color: "rgba(255, 255, 255, 0.72)",
		lineHeight: "1.7",
	},
	communitySection: {
		backgroundColor: "rgba(25, 25, 25, 0.82)",
		...shorthands.border("1px", "solid", "rgba(96, 174, 255, 0.3)"),
		...shorthands.borderRadius(tokens.borderRadiusLarge),
		...shorthands.padding("24px"),
		display: "grid",
		rowGap: "14px",
	},
	faqGrid: {
		display: "grid",
		gap: "12px",
		"@media (min-width: 900px)": {
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
		},
	},
	faqCard: {
		backgroundColor: "rgba(30, 30, 30, 0.78)",
		...shorthands.border("1px", "solid", "rgba(255, 255, 255, 0.075)"),
		...shorthands.borderRadius(tokens.borderRadiusLarge),
		...shorthands.padding("18px"),
		display: "grid",
		rowGap: "8px",
	},
	faqCardWide: {
		"@media (min-width: 900px)": {
			gridColumn: "1 / -1",
		},
	},
	faqQuestion: {
		marginTop: "0",
		marginBottom: "0",
		color: "rgba(255, 255, 255, 0.92)",
		fontWeight: tokens.fontWeightSemibold,
	},
	faqAnswer: {
		marginTop: "0",
		marginBottom: "0",
		color: "rgba(255, 255, 255, 0.62)",
		lineHeight: "1.7",
	},
	widgetList: {
		display: "flex",
		flexWrap: "wrap",
		gap: "8px",
	},
	footer: {
		color: "rgba(255, 255, 255, 0.34)",
		textAlign: "center",
		...shorthands.padding("8px", "0", "0", "0"),
	},
	lightboxSurface: {
		padding: 0,
		backgroundColor: "rgba(0, 0, 0, 0.95)",
		maxWidth: "100vw",
		maxHeight: "100vh",
		width: "100vw",
		height: "100vh",
		...shorthands.border("0"),
		boxShadow: "none",
	},
	lightboxContent: {
		height: "100%",
		width: "100%",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		overflow: "hidden",
		position: "relative",
		...shorthands.padding(0),
	},
	lightboxBody: {
		width: "100%",
		height: "100%",
		...shorthands.padding(0),
	},
	lightboxImage: {
		maxWidth: "100%",
		maxHeight: "100%",
		objectFit: "contain",
	},
	closeButton: {
		position: "absolute",
		top: "20px",
		right: "20px",
		zIndex: "1000",
		backgroundColor: "rgba(0, 0, 0, 0.5)",
		color: "#ffffff",
		":hover": {
			backgroundColor: "rgba(255, 255, 255, 0.1)",
			color: "#ffffff",
		},
	},
	clickableScreenshot: {
		cursor: "zoom-in",
	},
	screenshotButton: {
		backgroundColor: "transparent",
		...shorthands.border("0"),
		paddingTop: "0",
		paddingRight: "0",
		paddingBottom: "0",
		paddingLeft: "0",
		width: "100%",
		display: "block",
		textAlign: "left",
	},
	storeBadgeContainer: {
		marginTop: "10px",
	},
	storeBadgeImage: {
		display: "block",
	},
	lightboxTransformRoot: {
		width: "100%",
		height: "100%",
	},
	lightboxTransformWrapper: {
		width: "100%",
		height: "100%",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
	},
});
